const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const DBKEY='ihviajei_v2_db', SESSION='ihviajei_v2_session';
const db=()=>JSON.parse(localStorage.getItem(DBKEY)||'{"users":[],"trips":[],"purchases":[],"alerts":[]}');
const save=d=>localStorage.setItem(DBKEY,JSON.stringify(d)); const uid=()=>Math.random().toString(36).slice(2)+Date.now().toString(36);
function toast(t){let e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function currentUser(){let id=localStorage.getItem(SESSION),d=db();return d.users.find(u=>u.id===id)||null}
function seed(){let d=db();if(!d.users.length){let u={id:'demo',name:'Viajante Demo',email:'demo@ihviajei.com',password:'demo123',notify:'App e e-mail'};d.users.push(u);d.trips.push({id:'tripdemo',userId:'demo',name:'Europa 2027',start:'2027-05-28',end:'2027-06-16',destinations:'Portugal, Espanha, Itália, Suíça',travelers:2,profile:'Confortável',currency:'EUR',goal:4000});d.purchases.push({id:'p1',userId:'demo',tripId:'tripdemo',date:'2026-09-01',currency:'EUR',amount:1000,rate:6.28,institution:'Registro manual'});d.alerts.push({id:'a1',userId:'demo',type:'Euro abaixo de R$ 6,30',active:true},{id:'a2',userId:'demo',type:'Radar acima de 80',active:true});save(d)}}seed();
let authMode='login'; function showPublic(which='home'){ $('#appShell').classList.add('hidden');$('#publicShell').classList.remove('hidden'); if(which==='home'){ $('#publicHome').classList.remove('hidden');$('#authSection').classList.add('hidden');return} $('#publicHome').classList.add('hidden');$('#authSection').classList.remove('hidden');authMode=which;let reg=which==='register';$('#authTitle').textContent=reg?'Criar conta':'Entrar';$('#authDesc').textContent=reg?'Crie sua área pessoal para guardar suas viagens.':'Acesse suas viagens e metas.';$('#nameField').classList.toggle('hidden',!reg);$('#authSubmit').textContent=reg?'Criar minha conta':'Entrar';$('#authSwitch').textContent=reg?'Já tenho uma conta':'Criar uma conta';}
$$('[data-public]').forEach(b=>b.onclick=()=>showPublic(b.dataset.public));$('#authSwitch').onclick=()=>showPublic(authMode==='login'?'register':'login');
$('#authForm').onsubmit=e=>{e.preventDefault();let d=db(),email=$('#authEmail').value.trim().toLowerCase(),pass=$('#authPassword').value;if(authMode==='register'){if(d.users.some(u=>u.email===email))return toast('Este e-mail já está cadastrado.');let u={id:uid(),name:$('#authName').value.trim()||'Viajante',email,password:pass,notify:'App e e-mail'};d.users.push(u);save(d);localStorage.setItem(SESSION,u.id);openApp()}else{let u=d.users.find(u=>u.email===email&&u.password===pass);if(!u)return toast('E-mail ou senha inválidos.');localStorage.setItem(SESSION,u.id);openApp()}};
function openApp(){let u=currentUser();if(!u)return showPublic('home');$('#publicShell').classList.add('hidden');$('#appShell').classList.remove('hidden');$('#headerName').textContent=u.name;$('#avatar').textContent=(u.name[0]||'V').toUpperCase();$('#profileName').value=u.name;$('#profileEmail').value=u.email;$('#profileNotify').value=u.notify||'App e e-mail';$('#welcome').textContent='Olá, '+u.name.split(' ')[0]+'!';renderAll()}
$('#logoutBtn').onclick=()=>{localStorage.removeItem(SESSION);showPublic('home')};$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('mobile-open');
$$('[data-view]').forEach(b=>b.onclick=()=>{let id=b.dataset.view;$$('.view').forEach(v=>v.classList.remove('active'));$('#'+id).classList.add('active');$$('[data-view]').forEach(x=>x.classList.toggle('active',x===b));$('#sidebar').classList.remove('mobile-open');scrollTo(0,0)});
function mine(type){let u=currentUser(),d=db();return d[type].filter(x=>x.userId===u.id)} function sym(c){return c==='USD'?'US$':'€'} function brl(n){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(n)} function dateBR(s){if(!s)return '—';return new Date(s+'T12:00').toLocaleDateString('pt-BR')}
function purchaseStats(trip){let ps=mine('purchases').filter(p=>!trip||p.tripId===trip.id),amount=ps.reduce((a,p)=>a+p.amount,0),total=ps.reduce((a,p)=>a+p.amount*p.rate,0);return{amount,total,avg:amount?total/amount:0,count:ps.length}}
function renderAll(){let trips=mine('trips').sort((a,b)=>a.start.localeCompare(b.start)),alerts=mine('alerts'),next=trips.find(t=>new Date(t.end+'T23:59')>=new Date())||trips[0];$('#kpiAlerts').textContent=alerts.filter(a=>a.active).length;if(next){let st=purchaseStats(next),pct=next.goal?Math.min(100,st.amount/next.goal*100):0;$('#kpiTrip').textContent=next.name;$('#kpiDate').textContent=dateBR(next.start)+' → '+dateBR(next.end);$('#kpiGoal').textContent=sym(next.currency)+' '+Number(next.goal).toLocaleString('pt-BR');$('#kpiGoalPct').textContent=Math.round(pct)+'% comprado';let left=Math.max(0,next.goal-st.amount),suggest=Math.round(left*.25/50)*50;$('#strategy').textContent=left?`Você já registrou ${sym(next.currency)} ${st.amount.toLocaleString('pt-BR')} e ainda faltam ${sym(next.currency)} ${left.toLocaleString('pt-BR')}. Com Radar demonstrativo em 82/100, uma compra gradual ilustrativa seria cerca de ${sym(next.currency)} ${suggest.toLocaleString('pt-BR')}.`:'Sua meta cambial registrada já foi atingida.'}else{$('#kpiTrip').textContent='—';$('#kpiDate').textContent='Cadastre uma viagem';$('#kpiGoal').textContent='—';$('#kpiGoalPct').textContent='0% comprado';$('#strategy').textContent='Cadastre uma viagem e uma meta para receber uma sugestão de compra gradual.'} renderTrips(trips);renderWallet();renderAlerts()}
function tripHTML(t){let st=purchaseStats(t),pct=t.goal?Math.min(100,st.amount/t.goal*100):0;return `<div class="trip-card"><div><span class="pill">${new Date(t.end+'T23:59')>=new Date()?'EM PLANEJAMENTO':'CONCLUÍDA'}</span><h3>${esc(t.name)}</h3><span class="muted">${esc(t.destinations)} • ${dateBR(t.start)} → ${dateBR(t.end)}</span></div><div><small class="muted">Meta ${sym(t.currency)} ${Number(t.goal).toLocaleString('pt-BR')}</small><div class="mini-progress"><i style="width:${pct}%"></i></div><b>${Math.round(pct)}% comprado</b></div><div class="actions"><button class="btn" onclick="editTrip('${t.id}')">Editar</button><button class="btn danger" onclick="deleteTrip('${t.id}')">Excluir</button></div></div>`}
function renderTrips(trips=mine('trips')){$('#tripList').innerHTML=trips.length?trips.map(tripHTML).join(''):'<div class="panel empty">Você ainda não cadastrou nenhuma viagem.</div>';$('#dashTrips').innerHTML=trips.length?trips.slice(0,3).map(tripHTML).join(''):'<div class="empty">Crie sua primeira viagem para começar o planejamento.</div>'}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function modal(title,body){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=body;$('#modal').classList.remove('hidden')} $('#modalClose').onclick=()=>$('#modal').classList.add('hidden');$('#modal').onclick=e=>{if(e.target===$('#modal'))$('#modal').classList.add('hidden')}
function tripForm(t={}){modal(t.id?'Editar viagem':'Nova viagem',`<form id="tripForm" class="form-grid"><label>Nome<input name="name" required value="${esc(t.name||'')}"></label><label>Viajantes<input name="travelers" type="number" min="1" value="${t.travelers||1}"></label><label>Ida<input name="start" type="date" required value="${t.start||''}"></label><label>Volta<input name="end" type="date" required value="${t.end||''}"></label><label class="wide">Destinos<input name="destinations" required value="${esc(t.destinations||'')}"></label><label>Perfil<select name="profile"><option>Econômico</option><option ${t.profile==='Confortável'?'selected':''}>Confortável</option><option ${t.profile==='Premium'?'selected':''}>Premium</option></select></label><label>Moeda<select name="currency"><option value="EUR">Euro (€)</option><option value="USD" ${t.currency==='USD'?'selected':''}>Dólar (US$)</option></select></label><label>Meta em moeda<input name="goal" type="number" min="0" required value="${t.goal||4000}"></label><div class="wide actions"><button class="btn primary">Salvar viagem</button></div></form>`);$('#tripForm').onsubmit=e=>{e.preventDefault();let f=new FormData(e.target);if(f.get('end')<f.get('start'))return toast('A volta deve ser depois da ida.');let d=db(),u=currentUser(),obj=Object.fromEntries(f.entries());obj.travelers=+obj.travelers;obj.goal=+obj.goal;if(t.id){let i=d.trips.findIndex(x=>x.id===t.id&&x.userId===u.id);d.trips[i]={...d.trips[i],...obj}}else d.trips.push({id:uid(),userId:u.id,...obj});save(d);$('#modal').classList.add('hidden');renderAll();toast('Viagem salva.')}}
$$('[data-action="new-trip"]').forEach(b=>b.onclick=()=>tripForm());window.editTrip=id=>{let t=mine('trips').find(x=>x.id===id);if(t)tripForm(t)};window.deleteTrip=id=>{if(!confirm('Excluir esta viagem e desvincular seus registros?'))return;let d=db(),u=currentUser();d.trips=d.trips.filter(t=>!(t.id===id&&t.userId===u.id));d.purchases=d.purchases.filter(p=>!(p.tripId===id&&p.userId===u.id));save(d);renderAll();toast('Viagem excluída.')};
function renderWallet(){let ps=mine('purchases').sort((a,b)=>b.date.localeCompare(a.date)),st=purchaseStats();$('#walletTotal').textContent='€ '+st.amount.toLocaleString('pt-BR');$('#walletAvg').textContent=brl(st.avg);$('#walletBRL').textContent=brl(st.total);$('#walletCount').textContent=st.count;$('#purchaseRows').innerHTML=ps.length?ps.map(p=>`<tr><td>${dateBR(p.date)}</td><td>${p.currency}</td><td>${sym(p.currency)} ${p.amount.toLocaleString('pt-BR')}</td><td>${brl(p.rate)}</td><td>${brl(p.amount*p.rate)}</td><td>${esc(p.institution||'Manual')}</td></tr>`).join(''):'<tr><td colspan="6" class="empty">Nenhuma compra registrada.</td></tr>'}
$('#newPurchase').onclick=()=>{let trips=mine('trips');if(!trips.length)return toast('Crie uma viagem primeiro.');modal('Registrar compra',`<form id="purchaseForm" class="form-grid"><label>Viagem<select name="tripId">${trips.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('')}</select></label><label>Data<input name="date" type="date" required value="${new Date().toISOString().slice(0,10)}"></label><label>Quantidade<input name="amount" type="number" min="0.01" step="0.01" required></label><label>VET / taxa paga (R$)<input name="rate" type="number" min="0.01" step="0.0001" required></label><label class="wide">Instituição / origem<input name="institution" value="Registro manual"></label><div class="wide actions"><button class="btn primary">Registrar</button></div></form>`);$('#purchaseForm').onsubmit=e=>{e.preventDefault();let f=Object.fromEntries(new FormData(e.target).entries()),d=db(),t=trips.find(x=>x.id===f.tripId);d.purchases.push({id:uid(),userId:currentUser().id,...f,currency:t.currency,amount:+f.amount,rate:+f.rate});save(d);$('#modal').classList.add('hidden');renderAll();toast('Compra registrada.')}};
function renderAlerts(){let as=mine('alerts');$('#alertRows').innerHTML=as.length?as.map(a=>`<div class="alert-row"><div><b>${esc(a.type)}</b><div class="muted">${a.active?'Ativo':'Pausado'}</div></div><button class="btn" onclick="toggleAlert('${a.id}')">${a.active?'Pausar':'Ativar'}</button></div>`).join(''):'<div class="empty">Nenhum alerta criado.</div>'} window.toggleAlert=id=>{let d=db(),a=d.alerts.find(x=>x.id===id&&x.userId===currentUser().id);if(a)a.active=!a.active;save(d);renderAll()};
$('#newAlert').onclick=()=>modal('Criar alerta',`<form id="alertForm" class="form-grid"><label class="wide">Tipo<select name="type"><option>Euro abaixo de R$ 6,30</option><option>Radar acima de 80</option><option>Queda de 2% em 7 dias</option><option>Dólar abaixo de R$ 5,30</option></select></label><div class="wide actions"><button class="btn primary">Criar alerta</button></div></form>`);document.addEventListener('submit',e=>{if(e.target.id!=='alertForm')return;e.preventDefault();let f=Object.fromEntries(new FormData(e.target).entries()),d=db();d.alerts.push({id:uid(),userId:currentUser().id,type:f.type,active:true});save(d);$('#modal').classList.add('hidden');renderAll();toast('Alerta criado.')});
$('#profileForm').onsubmit=e=>{e.preventDefault();let d=db(),u=d.users.find(x=>x.id===currentUser().id);u.name=$('#profileName').value.trim()||u.name;u.notify=$('#profileNotify').value;save(d);openApp();toast('Perfil atualizado.')};$$('.demoOffer').forEach(b=>b.onclick=()=>toast('Oferta demonstrativa: compra real ainda não está integrada.'));
if(currentUser())openApp();else showPublic('home');