'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert');
const server=fs.readFileSync(path.join(__dirname,'server.js'),'utf8');
const app=fs.readFileSync(path.join(__dirname,'public','app.js'),'utf8');
const html=fs.readFileSync(path.join(__dirname,'public','index.html'),'utf8');
const pkg=require('./package.json');
assert.equal(pkg.version,'139.0.0');
for(const token of ['assistant_proposals','emergency_info','expense_settlements','flight_watch_state','googleWalletLink','appleWalletBuffer','sendWebPushToUser','startFlightWatch','/report.pdf','/admin/mfa/setup','/auth/mfa','routeAwareConflicts'])assert.ok(server.includes(token),`v139 ausente: ${token}`);
for(const token of ['assistantProposalCard','emergencyBtn','report.pdf','settlementCheck','adminHealth','adminMfaBtn'])assert.ok(app.includes(token)||html.includes(token),`frontend v139 ausente: ${token}`);
assert.ok(fs.readFileSync(path.join(__dirname,'public','sw.js'),'utf8').includes('ihviajei-v139'));
assert.ok(fs.existsSync(path.join(__dirname,'V139-CHECKLIST.md')));
console.log('OK: escopo operacional v139, Wallet, Push, MFA, emergência, relatório e documentação validados estaticamente.');
